[options]
work_mode = "normal"
library = "GtkSource"
version = "3.0"
min_cfg_version = "3.4"
generate_safety_asserts = false
external_libraries = [
   "cairo",
   "Gdk",
   "GdkPixbuf",
   "Gio",
   "GLib",
   "Gtk",
   "Pango",
]

generate = [
   "GtkSource.BackgroundPatternType",
   "GtkSource.BracketMatchType",
   "GtkSource.Buffer",
   "GtkSource.ChangeCaseType",
   "GtkSource.Completion",
   "GtkSource.CompletionActivation",
   "GtkSource.CompletionContext",
   "GtkSource.CompletionError",
   "GtkSource.CompletionInfo",
   "GtkSource.CompletionItem",
   "GtkSource.CompletionProposal",
   "GtkSource.CompletionProvider",
   "GtkSource.CompletionWords",
   "GtkSource.CompressionType",
   "GtkSource.DrawSpacesFlags",
   "GtkSource.File",
   "GtkSource.FileLoader",
   "GtkSource.FileLoaderError",
   "GtkSource.FileSaver",
   "GtkSource.FileSaverError",
   "GtkSource.FileSaverFlags",
   "GtkSource.GutterRenderer",
   "GtkSource.GutterRendererAlignmentMode",
   "GtkSource.GutterRendererPixbuf",
   "GtkSource.GutterRendererState",
   "GtkSource.GutterRendererText",
   "GtkSource.Language",
   "GtkSource.LanguageManager",
   "GtkSource.Map",
   "GtkSource.Mark",
   "GtkSource.MarkAttributes",
   "GtkSource.NewlineType",
   "GtkSource.PrintCompositor",
   "GtkSource.SearchContext",
   "GtkSource.SearchSettings",
   "GtkSource.SmartHomeEndType",
   "GtkSource.SortFlags",
   "GtkSource.SpaceDrawer",
   "GtkSource.SpaceLocationFlags",
   "GtkSource.SpaceTypeFlags",
   "GtkSource.StyleScheme",
   "GtkSource.StyleSchemeChooser",
   "GtkSource.StyleSchemeChooserButton",
   "GtkSource.StyleSchemeChooserWidget",
   "GtkSource.StyleSchemeManager",
   "GtkSource.Tag",
   "GtkSource.UndoManager",
   "GtkSource.ViewGutterPosition",
]

manual = [
   "cairo.Context",
   "Gdk.Event",
   "Gdk.Rectangle",
   "Gdk.RGBA",
   "Gdk.Window",
   "Gio.Settings",
   "Gio.SettingsBindFlags",
   "GLib.Error",
   "GLib.Variant",
   "Gtk.ScrollStep",
   "Gtk.TextTagTable",
   "Gtk.TextView",
   "Gtk.Scrollable",
   "Gtk.TextBuffer",
   "Gtk.TextMark",
   "Gtk.TextTag",
   "Gtk.TextWindowType",
   "Gtk.Tooltip",
   "Gtk.Unit",
   "Gtk.Widget",
   "Gtk.WrapMode",
   "Pango.Underline",
]

[[object]]
name = "GtkSource.Gutter"
status = "generate"
    [[object.function]]
    name = "get_padding"
    ignore = true

[[object]]
name = "GtkSource.View"
status = "generate"
    [[object.function]]
    name = "get_mark_attributes"
    ignore = true
