// This file was generated by gir (b010d34) from gir-files (71d73f0)
// DO NOT EDIT

#[cfg(feature = "v3_10")]
use Buffer;
#[cfg(feature = "v3_10")]
use Error;
#[cfg(feature = "v3_10")]
use SearchSettings;
use ffi;
use glib::object::IsA;
use glib::translate::*;
#[cfg(feature = "v3_10")]
use std::ptr;

glib_wrapper! {
    pub struct SearchContext(Object<ffi::GtkSourceSearchContext>);

    match fn {
        get_type => || ffi::gtk_source_search_context_get_type(),
    }
}

impl SearchContext {
    #[cfg(feature = "v3_10")]
    pub fn new<'a, P: Into<Option<&'a SearchSettings>>>(buffer: &Buffer, settings: P) -> SearchContext {
        let settings = settings.into();
        let settings = settings.to_glib_none();
        unsafe {
            from_glib_full(ffi::gtk_source_search_context_new(buffer.to_glib_none().0, settings.0))
        }
    }
}

pub trait SearchContextExt {
    //#[cfg(feature = "v3_10")]
    //fn backward(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> bool;

    //#[cfg(feature = "v3_22")]
    //fn backward2(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Option<bool>;

    //#[cfg(feature = "v3_10")]
    //fn backward_async<'a, 'b, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::AsyncReadyCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(&self, iter: /*Ignored*/&gtk::TextIter, cancellable: P, callback: Q, user_data: R);

    //#[cfg(feature = "v3_10")]
    //fn backward_finish<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<(), Error>;

    //#[cfg(feature = "v3_22")]
    //fn backward_finish2<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<bool, Error>;

    //#[cfg(feature = "v3_10")]
    //fn forward(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> bool;

    //#[cfg(feature = "v3_22")]
    //fn forward2(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Option<bool>;

    //#[cfg(feature = "v3_10")]
    //fn forward_async<'a, 'b, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::AsyncReadyCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(&self, iter: /*Ignored*/&gtk::TextIter, cancellable: P, callback: Q, user_data: R);

    //#[cfg(feature = "v3_10")]
    //fn forward_finish<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<(), Error>;

    //#[cfg(feature = "v3_22")]
    //fn forward_finish2<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<bool, Error>;

    #[cfg(feature = "v3_10")]
    fn get_buffer(&self) -> Option<Buffer>;

    #[cfg(feature = "v3_10")]
    fn get_highlight(&self) -> bool;

    //#[cfg(feature = "v3_16")]
    //fn get_match_style(&self) -> /*Ignored*/Option<Style>;

    //#[cfg(feature = "v3_10")]
    //fn get_occurrence_position(&self, match_start: /*Ignored*/&gtk::TextIter, match_end: /*Ignored*/&gtk::TextIter) -> i32;

    #[cfg(feature = "v3_10")]
    fn get_occurrences_count(&self) -> i32;

    #[cfg(feature = "v3_10")]
    fn get_regex_error(&self) -> Option<Error>;

    #[cfg(feature = "v3_10")]
    fn get_settings(&self) -> Option<SearchSettings>;

    //#[cfg(feature = "v3_10")]
    //fn replace(&self, match_start: /*Ignored*/&gtk::TextIter, match_end: /*Ignored*/&gtk::TextIter, replace: &str, replace_length: i32) -> Result<(), Error>;

    //#[cfg(feature = "v3_22")]
    //fn replace2(&self, match_start: /*Ignored*/&mut gtk::TextIter, match_end: /*Ignored*/&mut gtk::TextIter, replace: &str, replace_length: i32) -> Result<(), Error>;

    #[cfg(feature = "v3_10")]
    fn replace_all(&self, replace: &str, replace_length: i32) -> Result<(), Error>;

    #[cfg(feature = "v3_10")]
    fn set_highlight(&self, highlight: bool);

    //#[cfg(feature = "v3_16")]
    //fn set_match_style<'a, P: Into<Option<&'a /*Ignored*/Style>>>(&self, match_style: P);

    #[cfg(feature = "v3_10")]
    fn set_settings<'a, P: Into<Option<&'a SearchSettings>>>(&self, settings: P);
}

impl<O: IsA<SearchContext>> SearchContextExt for O {
    //#[cfg(feature = "v3_10")]
    //fn backward(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> bool {
    //    unsafe { TODO: call ffi::gtk_source_search_context_backward() }
    //}

    //#[cfg(feature = "v3_22")]
    //fn backward2(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Option<bool> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_backward2() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn backward_async<'a, 'b, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::AsyncReadyCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(&self, iter: /*Ignored*/&gtk::TextIter, cancellable: P, callback: Q, user_data: R) {
    //    unsafe { TODO: call ffi::gtk_source_search_context_backward_async() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn backward_finish<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<(), Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_backward_finish() }
    //}

    //#[cfg(feature = "v3_22")]
    //fn backward_finish2<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<bool, Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_backward_finish2() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn forward(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> bool {
    //    unsafe { TODO: call ffi::gtk_source_search_context_forward() }
    //}

    //#[cfg(feature = "v3_22")]
    //fn forward2(&self, iter: /*Ignored*/&gtk::TextIter, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Option<bool> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_forward2() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn forward_async<'a, 'b, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::AsyncReadyCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(&self, iter: /*Ignored*/&gtk::TextIter, cancellable: P, callback: Q, user_data: R) {
    //    unsafe { TODO: call ffi::gtk_source_search_context_forward_async() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn forward_finish<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<(), Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_forward_finish() }
    //}

    //#[cfg(feature = "v3_22")]
    //fn forward_finish2<P: IsA</*Ignored*/gio::AsyncResult>>(&self, result: &P, match_start: /*Ignored*/gtk::TextIter, match_end: /*Ignored*/gtk::TextIter) -> Result<bool, Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_forward_finish2() }
    //}

    #[cfg(feature = "v3_10")]
    fn get_buffer(&self) -> Option<Buffer> {
        unsafe {
            from_glib_none(ffi::gtk_source_search_context_get_buffer(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v3_10")]
    fn get_highlight(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_source_search_context_get_highlight(self.to_glib_none().0))
        }
    }

    //#[cfg(feature = "v3_16")]
    //fn get_match_style(&self) -> /*Ignored*/Option<Style> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_get_match_style() }
    //}

    //#[cfg(feature = "v3_10")]
    //fn get_occurrence_position(&self, match_start: /*Ignored*/&gtk::TextIter, match_end: /*Ignored*/&gtk::TextIter) -> i32 {
    //    unsafe { TODO: call ffi::gtk_source_search_context_get_occurrence_position() }
    //}

    #[cfg(feature = "v3_10")]
    fn get_occurrences_count(&self) -> i32 {
        unsafe {
            ffi::gtk_source_search_context_get_occurrences_count(self.to_glib_none().0)
        }
    }

    #[cfg(feature = "v3_10")]
    fn get_regex_error(&self) -> Option<Error> {
        unsafe {
            from_glib_full(ffi::gtk_source_search_context_get_regex_error(self.to_glib_none().0))
        }
    }

    #[cfg(feature = "v3_10")]
    fn get_settings(&self) -> Option<SearchSettings> {
        unsafe {
            from_glib_none(ffi::gtk_source_search_context_get_settings(self.to_glib_none().0))
        }
    }

    //#[cfg(feature = "v3_10")]
    //fn replace(&self, match_start: /*Ignored*/&gtk::TextIter, match_end: /*Ignored*/&gtk::TextIter, replace: &str, replace_length: i32) -> Result<(), Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_replace() }
    //}

    //#[cfg(feature = "v3_22")]
    //fn replace2(&self, match_start: /*Ignored*/&mut gtk::TextIter, match_end: /*Ignored*/&mut gtk::TextIter, replace: &str, replace_length: i32) -> Result<(), Error> {
    //    unsafe { TODO: call ffi::gtk_source_search_context_replace2() }
    //}

    #[cfg(feature = "v3_10")]
    fn replace_all(&self, replace: &str, replace_length: i32) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::gtk_source_search_context_replace_all(self.to_glib_none().0, replace.to_glib_none().0, replace_length, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[cfg(feature = "v3_10")]
    fn set_highlight(&self, highlight: bool) {
        unsafe {
            ffi::gtk_source_search_context_set_highlight(self.to_glib_none().0, highlight.to_glib());
        }
    }

    //#[cfg(feature = "v3_16")]
    //fn set_match_style<'a, P: Into<Option<&'a /*Ignored*/Style>>>(&self, match_style: P) {
    //    unsafe { TODO: call ffi::gtk_source_search_context_set_match_style() }
    //}

    #[cfg(feature = "v3_10")]
    fn set_settings<'a, P: Into<Option<&'a SearchSettings>>>(&self, settings: P) {
        let settings = settings.into();
        let settings = settings.to_glib_none();
        unsafe {
            ffi::gtk_source_search_context_set_settings(self.to_glib_none().0, settings.0);
        }
    }
}
