// This file was generated by gir (b010d34) from gir-files (71d73f0)
// DO NOT EDIT

use StyleSchemeChooser;
use ffi;
use glib::object::Downcast;
use glib::translate::*;
use gtk;
use gtk_ffi;

glib_wrapper! {
    pub struct StyleSchemeChooserButton(Object<ffi::GtkSourceStyleSchemeChooserButton>): [
        gtk::Widget => gtk_ffi::GtkWidget,
        StyleSchemeChooser,
    ];

    match fn {
        get_type => || ffi::gtk_source_style_scheme_chooser_button_get_type(),
    }
}

impl StyleSchemeChooserButton {
    #[cfg(feature = "v3_16")]
    pub fn new() -> StyleSchemeChooserButton {
        unsafe {
            gtk::Widget::from_glib_none(ffi::gtk_source_style_scheme_chooser_button_new()).downcast_unchecked()
        }
    }
}
